In [3]:
import os

In [20]:
import pandas as pd

In [4]:
def list_files_in_folder(folder_path):
    for root, dirs, files in os.walk(folder_path):
        for file in files:
            print(os.path.join(root, file))

list_files_in_folder("/PegaPlantão/03 2023")

In [5]:
for i in list_files_in_folder("C:/Users/Gabriel/Documents//PegaPlantão/03 2023"):
    print(i)

C:/Users/Gabriel/Documents//PegaPlantão/03 2023\Novo(a) Planilha do Microsoft Excel.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\~$Novo(a) Planilha do Microsoft Excel.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(01a07)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(01a07)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(01a07)\df_gabs2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(01a07)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(01a07)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(07a09)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(07a09)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(07a09)\df_gabs2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(07a09)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(07a09)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(09a13)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(09a13)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(09a13)\df_gabs2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(09a13)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(09a13)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(13a16)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(13a16)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(13a16)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(13a16)\df_giov2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(13a16)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(16a20)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(16a20)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(16a20)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(16a20)\df_giov2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(16a20)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(20a27)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(20a27)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(20a27)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(20a27)\df_giov2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(20a27)\_chat.txt
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(27a29)\df.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(27a29)\df_gabs.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(27a29)\df_giov.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(27a29)\df_giov2.xlsx
C:/Users/Gabriel/Documents//PegaPlantão/03 2023\03(27a29)\_chat.txt

TypeError: 'NoneType' object is not iterable

In [6]:
import os

diretorio_atual = os.getcwd()  # obtém o diretório atual
pastas = [nome for nome in os.listdir(diretorio_atual) if os.path.isdir(os.path.join(diretorio_atual, nome))]

print(pastas)

['.ipynb_checkpoints', '01 2023', '02 2023', '03 2023', 'Copia segurança', 'Driver_Notes']

In [5]:
print(os.getcwd())

C:\Users\Gabriel\Documents\PegaPlantão

In [26]:

pastas

['03(01a07)',
 '03(07a09)',
 '03(09a13)',
 '03(13a16)',
 '03(16a20)',
 '03(20a27)',
 '03(27a29)']

In [45]:
fd = pd.DataFrame(columns=['nome', "mensagem", 'endereço'])

caminho = "C:/Users/Gabriel/Documents//PegaPlantão/03 2023"  # diretório atual, pode ser substituído pelo caminho desejado
pastas = next(os.walk(caminho))[1]

for pasta in pastas:
    caminho_1 = caminho+"/"+pasta
    #print(pasta, '='*10)
    for i in next(os.walk(caminho_1))[2]:
        if (i == 'df_giov.xlsx') or (i == 'df_giov2.xlsx'):
            caminho_2 = caminho+"/"+pasta+"/"+i
            
            df = pd.read_excel(caminho_2, usecols=['nome', "mensagem", ])
            print(pasta, '->', i, '->', len(df))
            
            df['endereço'] = pasta+' -> '+i+' -> '+str(len(df))
            
            fd = pd.concat([fd, df])
            fd.reset_index(drop=True, inplace=True)
            
fd

03(01a07) -> df_giov.xlsx -> 117
03(07a09) -> df_giov.xlsx -> 25
03(09a13) -> df_giov.xlsx -> 56
03(09a13) -> df_giov2.xlsx -> 29
03(13a16) -> df_giov.xlsx -> 43
03(13a16) -> df_giov2.xlsx -> 21
03(16a20) -> df_giov.xlsx -> 49
03(16a20) -> df_giov2.xlsx -> 28
03(20a27) -> df_giov.xlsx -> 80
03(20a27) -> df_giov2.xlsx -> 59
03(27a29) -> df_giov.xlsx -> 23
03(27a29) -> df_giov2.xlsx -> 14

,nome,mensagem,endereço
0,MATHEUS CARDOZO JANIQUES,‎Rodrigo Giovanelli Constantino adicionou Math...,03(01a07) -> df_giov.xlsx -> 117
1,BRUNO STORNIOLI TAGUCHI LEMOS,Jabaquara Bruno Lemos entrada 06:00,03(01a07) -> df_giov.xlsx -> 117
2,BRUNO STORNIOLI TAGUCHI LEMOS,Jabaquara Bruno Lemos saída 16:10,03(01a07) -> df_giov.xlsx -> 117
3,KAREN CAVICHINI ROSSETO,04/03 - Karen Cavichini - Jabaquara entrada 0...,03(01a07) -> df_giov.xlsx -> 117
4,RENATA TOGEIRO BASTOS GODOY DE FARIA,(D2R),03(01a07) -> df_giov.xlsx -> 117
...,...,...,...
539,NATAN SOARES SILVEIRA,27/08 - Anália- Natan - entrada 07:20 ( atras...,03(27a29) -> df_giov2.xlsx -> 14
540,RENATO VIEIRA RODRIGUES DE OLIVEIRA,28/03 Morumbi - Vieira Saída 16h03,03(27a29) -> df_giov2.xlsx -> 14
541,ROMULO SPOLIDORIO,28/03 Jabaquara - Rômulo - saída 14:40,03(27a29) -> df_giov2.xlsx -> 14
542,THAYS GUIMARAES BADARO,29/03 Osasco - Badaro Entrada 05:40,03(27a29) -> df_giov2.xlsx -> 14
543,TURIBIO RODRIGUES FREIRE NETO,28/03 Morumbi - Turíbio Saida: 15:40,03(27a29) -> df_giov2.xlsx -> 14

In [47]:
fd = fd[fd['endereço'] != '03(01a07) -> df_giov.xlsx -> 117']

In [50]:
fd = fd.reset_index()
fd

,level_0,index,nome,mensagem,endereço
0,0,117,ANDRE MORTARI PLA GIL,07/03 EINSTEIN André entrada 17:30h 07/03 EINS...,03(07a09) -> df_giov.xlsx -> 25
1,1,118,GUSTAVO MARQUES DA SILVA,Deslocado Itaim,03(07a09) -> df_giov.xlsx -> 25
2,2,119,NORIVAL SCANDELAI JUNIOR,Deslocado Itaim,03(07a09) -> df_giov.xlsx -> 25
3,3,120,RODRIGO GOMES MINAS NOVAS,07/03 AVICCENA Gomes saída 16:45 (deslocamento...,03(07a09) -> df_giov.xlsx -> 25
4,4,121,NATALIA MAIA QUEIROZ,07/03-Santa Isabel -Queiroz saída 18:45 (deslo...,03(07a09) -> df_giov.xlsx -> 25
...,...,...,...,...,...
422,422,539,NATAN SOARES SILVEIRA,27/08 - Anália- Natan - entrada 07:20 ( atras...,03(27a29) -> df_giov2.xlsx -> 14
423,423,540,RENATO VIEIRA RODRIGUES DE OLIVEIRA,28/03 Morumbi - Vieira Saída 16h03,03(27a29) -> df_giov2.xlsx -> 14
424,424,541,ROMULO SPOLIDORIO,28/03 Jabaquara - Rômulo - saída 14:40,03(27a29) -> df_giov2.xlsx -> 14
425,425,542,THAYS GUIMARAES BADARO,29/03 Osasco - Badaro Entrada 05:40,03(27a29) -> df_giov2.xlsx -> 14
426,426,543,TURIBIO RODRIGUES FREIRE NETO,28/03 Morumbi - Turíbio Saida: 15:40,03(27a29) -> df_giov2.xlsx -> 14

In [2]:
import pandas as pd
fd = pd.read_excel('df_giov.xlsx')
fd

,chat,dia,nome,mensagem
0,[01/06/2023 05:30:07] Gretel Oliveira Nicolau:...,01/06/2023,GRETEL OLIVEIRA NICOLAU,01/06 Analia - Gretel entrada 4: 40
1,[01/06/2023 11:11:56] Orlando Domingues de Ara...,01/06/2023,ORLANDO DOMINGUES DE ARAUJO PONTES,01/06 Aviccena Orlando saida 07:30 ( motivo...
2,[01/06/2023 12:47:06] Larissa Mayumi Ono: 01/0...,01/06/2023,LARISSA MAYUMI ONO,01/06 Osasco Larissa - saída 12:45 ( desl...
3,[01/06/2023 20:25:49] Lívia Schenkel Thurler T...,01/06/2023,LIVIA SCHENKEL THURLER TRAIRI,01/06 VILLA - Livia dispensa
4,[01/06/2023 21:21:10] Felipe Coelho de Souza: ...,01/06/2023,FELIPE COELHO DE SOUZA,01/06 Osasco - Coelho 21:10
...,...,...,...,...
114,[20/06/2023 18:19:47] Alexandre Bernardino: 20...,20/06/2023,ALEXANDRE BERNARDINO,20/06 Sta Isabel - Alexandre - entrada 05:40
115,[20/06/2023 23:13:59] Renata Pinheiro Modolo: ...,20/06/2023,RENATA PINHEIRO MODOLO,20/06 Itaim R. Modolo 19:40
116,[21/06/2023 06:12:00] Marina Pontes Moura Nasc...,21/06/2023,MARINA PONTES MOURA NASCIMENTO E SILVA,21/06 Osasco Moura entrada 6h
117,[21/06/2023 13:02:00] Felipe Coelho de Souza: ...,21/06/2023,FELIPE COELHO DE SOUZA,21/06 Itaim - Coelho saída 13:00 ( pós pl...
118,[22/06/2023 13:00:40] Vivianna Bovério Galzera...,22/06/2023,VIVIANNA BOVERIO GALZERANI,22/06 Osasco Vivianna saída 13:00 ( desloca...

In [3]:
for nome in sorted(list(fd['nome'].unique())):
    print(nome, "="*10)
    selecao = fd.loc[fd['nome']==nome]
    selecao.reset_index(drop=True, inplace=True)
    
    for i in range(len(selecao)):
        print(selecao["mensagem"][i])
    
    print("\n")

ALEXANDRE BERNARDINO ==========
08/06  -  Aviccena  -  Alexandre  -  saída 13:00
20/06 Sta Isabel  -  Alexandre  -  entrada 05:40


ANA GABRIELA GEWEHR VALE SALMEN ==========
12/06 Itaim  -  Vale saída 7:00   (  pós - plantão Maternidade  )


ANA JUNG DOCKO ==========
08/06 Analia Ana dispensada
18/06 Itaim Ana saída 19:00   (  D2  )


ANDREIA LOUREIRO MORI ==========
02/06 Jabaquara Andréia entrada 05: 15
05/06 Jabaquara Andréia saída 12:55


ANNA BEATRIZ LIMA DO VALLE ASTUR ==========
10/06 Morumbi  -  Astur dispensada


BEATRIZ ANTIPOU DOS SANTOS ==========
08/06 -  Maternidade -  Antipou -  dispensada


BIANCA PRISCILA BUNIOTTI ==========
04/06 Aviccena  -  Bianca saída 15:00   (  D2 Villa  )
08/06 Maternidade  -  Bianca dispensada


BRUCE YE MAN CHOW ==========
12/06 morumbi  -  bruce saida 12:35


BRUNO STORNIOLI TAGUCHI LEMOS ==========
03/06 Jabaquara Bruno Lemos saída 18:40


CAIO TULIO DUARTE ==========
02/06 Morumbi  -  Caio saída 10:50   (  por motivo de saúde  )


CAMILA CHIARANTANO HARRISON ==========
06/06 Villa Camila Dispensada
08/06 Villa Camila Dispensada


CARLOS AUGUSTO TREVISAN ==========
10/06 ITAIM Carlos dispensa


CARLOS EDUARDO CORREA GRILO ==========
14/06 Anália  -  Cadu 17:10


CAROLINE FIRMINO LEMES DA SILVA ==========
09/06 Osasco Lemes 13:40


DEBORA ALVES AUDE ==========
08:06 Itaim Débora saída 13:10


EDUARDO ARBACHE BEZERRA ==========
17/06 Itaim  -  Bezerra saida 12:50


EVERTON SIDNEY DA CONCEICAO CARVALHO ==========
12/06 Anália Everton saída 12:35   (  deslocado Itaim  )


FABIANA BARBOSA BASTOS ==========
06/06 Morumbi  -  Fabiana dispensada


FABIO ANTONIO DE SOUZA OLIVEIRA ==========
05/06 VNS Fábio entrada 6hs e saída 19:38
06/06 Itaim Fabio entrada 6hs
07/06 Itaim Fabio entrada 7hs e saída 14:15   (   anestesia a pedido  )


FELIPE COELHO DE SOUZA ==========
01/06 Osasco  -  Coelho 21:10
03/06 VNS Coelho  -  saída 12:40
21/06 Itaim  -  Coelho saída 13:00   (  pós plantão  )


FERNANDO RIBEIRO SA ==========
09/06 Jabaquara Ribeiro saída 12:45   (  deslocamento VNS  )


FILIPE LUGON MOULIN LIMA ==========
10/06 JABAQUARA  -  Filipe Lugon saida 12:55


FILIPE MAEDA HASHI ABDALLA MARTINS ==========
10/06 Jabaquara Maeda dispensa


FRANCISCO JOSE LUCENA BEZERRA ==========
20/06  -  JABAQUARA  -  Lucena entrada 15:00 20/06  -  JABAQUARA -  Lucena saída 17:00


GABRIELA RODRIGUES MACHADO BORJA ==========
17/06 Villa  -  Borja saída 19:00


GRETEL OLIVEIRA NICOLAU ==========
01/06 Analia -  Gretel entrada 4: 40


ISABELA MATTARELLI SOUZA CARLI ==========
13/06  -  Analia  -  Mattarelli saída 19:00


IZABELA CARDOSO GARCIA ==========
11/06 Itaim Garcia entrada 08:30 saída 11:00   (  d3  )


IZABELA CRISTINA ALMEIDA DUARTE ==========
08/06  Osasco Duarte saída 13:00


IZABELLA GONTIJO CUNHA ==========
03/06 MORUMBI  -  Izabella saída 13:00


JAIME ANDRES ARIAS CRIOLLO ==========
‎Você removeu Jaime Andres Arias Criollo


JESSICA LIDIA DE SOUZA ==========
09/06 JABAQUARA  -  Jessica 17:40
11/06 Itaim Jessica  entrada 07:00 saída 15:45   (  d2  )


JULIANA HUSSEIN GRILO ==========
06/06 VILLA  -  J. Hussein dispensada
07/06 VILLA  -  J. Hussein dispensada


KAREN CAVICHINI ROSSETO ==========
05/06 Villa/Osasco -  cavichini dispensada   (  pós plantão  )
12/06 Osaco  -  Cavichini entrada 05:35
16/06 Morumbi  -  Cavichini  entrada 07:00 e saída 14:00   (  EXTRA  )


KAREN YUMI MIYASHIRO ==========
10/06 VILLA  -  Yumi dispensada


LARISSA MAYUMI ONO ==========
01/06 Osasco Larissa  -  saída 12:45   (  deslocada Itaim  )


LAYSA LAYNA RIBEIRO LIMA ==========
08/06 Osasco Laysa saída 12h40
14/6 Jabaquara  -  Laysa entrada 6h


LEANDRO OLIVEIRA MARTINS CORTES ==========
09/06 ITAIM  -  Côrtes saída 12:45


LIVIA SCHENKEL THURLER TRAIRI ==========
01/06 VILLA  -  Livia dispensa
08/06 VILLA  -  Livia dispensada


LIVIA VALVERDE FAJARDO ==========
17/06 Jabaquara  -  Valverde saída 12:45


MANUELA AFFONSO FERREIRA SANGED ==========
03/06 Jabaquara  -  Manuela saída 18:40
13/06 Villa  -  Manuela saída 21h


MARCELA APARECIDA CORREA MARTINS ==========
09/06 Anália  -  Marcela Martins saída 12:47
Villa  -  Marcela Martins saída 15:40


MARCELA LEITE ROSIGNOLI ==========
08/06 Maternidade  -  Marcela Leite dispensada


MARCELO MAIA DA SILVEIRA ==========
19/06 VILLA   -  Maia saída 12:40


MARIANA GASPARELLI DE SOUZA ==========
19:06 Osasco  -  Mariana Gasparelli saída 12:15 ( deslocada Morumbi)


MARINA BORGES CURRALO ==========
16/6 Maternidade Marina entrada 6:30 16/6 Maternidade Marina saída  13:00


MARINA PONTES MOURA NASCIMENTO E SILVA ==========
12/06 Osasco moura saída 18:35
21/06 Osasco Moura entrada 6h


MATHEUS ACQUESTA GAUBEUR ==========
10/06 Villa  -  Matheus saída 12:50


MAXVILANO LIMA DE MACEDO ==========
17/06  -  Morumbi  -  Maxvilano  -  Entrada 06;00


MICHELLE DE OLIVEIRA CHAGAS ==========
04/06 Morumbi  -  Michelle entrada 6:05 D1 Osasco


MONICA ROBLES GONCALVES ==========
09/06 Itaim Mônica saída 12:45
11/06 Itaim Mônica entrada 08:00 saída 12:40   (  d3  )


NARA YAMANE DOS SANTOS ==========
10/06 villa  -  nara entrada 6h
12/06 osasco -  Nara dispensada   (   pos hsi  )
13/06 aviccena  -  nara entrada 6h


NATAN SOARES SILVEIRA ==========
Anália -  Natan  -  saída 15:55 (deslocado Aviccena/ pós plantão)


NATHALIA FANUCCI OLIVEIRA DI JORGE ==========
08/06 MORUMBI Nathália Dispensada
10/06 OSASCO Nathália Dispensada


ORLANDO DOMINGUES DE ARAUJO PONTES ==========
01/06 Aviccena Orlando saida 07:30   (  motivo de saude  )


PALOMA KIYOMI TAGUCHI ==========
08/06 JABAQUARA -  Paloma dispensada
07/06 JABAQUARA -  Paloma dispensada
09/06 JABAQUARA  -  Paloma dispensada
10/06 ANALIA  -  Paloma dispensada
13/06 JABAQUARA -  Paloma dispensada
14/06 JABAQUARA -  Paloma dispensada


PAULA LOPES AGAPITO DE FREITAS ==========
10/06  -  Anália  -  Paula A  -  dispensada


RENATA PINHEIRO MODOLO ==========
20/06 Itaim R. Modolo 19:40


RENATA TORRES BUENO ==========
05/06 Villa  -  Renata Bueno entrada 11:00 saída 22:10
12/06 Villa  -  Renata Bueno entrada 11:00 saída 18:50
Analia  -  Renata Bueno saída 18:15
19/06 Villa  -  Renata Bueno entrada 11:00 saída 22:40


RICARDO IVO DE LIMA ==========
17/06  -  VNS  -  Ricardo Ivo Entrada  -  12:00h Distância


RODRIGO ANDRADE CARMELLO ==========
13/06 Jabaquara  -  Carmello saida 18:50
18/06 Itaim  -  Carmello saida 21:40   (  D1 VNS  )


RODRIGO ANTONIO REY GONZALEZ ==========
OSASCO  -  Rey saida 15:50


RODRIGO MARTINS PEREIRA ==========
03/06 VILLA  -  pereira saída 18:32
07/06  -  OSASCO  -  pereira 06:00


ROMULO SPOLIDORIO ==========
03/06 Villa Rômulo saída 18:35
04/06  -  Anália  -  Rômulo  -  saída 19:55   (  D1 deslocado Villa  )
14/06 Jabquara  -  Rômulo entrada 06:50


RONALD FIGUEIREDO GOMES ==========
03/06 VILLA  -  Ronald saída 18:35


SABRINA DE SOUZA RAMOS ==========
08/06 Jabaquara Sabrina dispensada
10/06 Jabaquara Sabrina dispensada


SILVIA ALINE DOS SANTOS ANDRADE ==========
08/06  -  Itaim  -  Silvia dispensada


THAIS CHAVES PINHEIRO ==========
14/06 Itaim  -  Thaís saída 12:35


THAIS MIRANDA RAMOS ==========
02/06 OSASCO  -  Miranda entrada às 06h
02/06 OSASCO  -  Miranda saída às 17h
16/06 OSASCO  -  Miranda entrada às 06h
17/06 ITAIM  -  Miranda entrada às 06h


THALES LUVISOTTO NEDER ==========
03/06 Osasco  -  Thales saída 12:45   (  deslocado Itaim  )


THIAGO SILVA PINTO ==========
05/06 Jabaquara  -  T. Silva  -   saída 12:55
10/06 ANÁLIA T. Silva saída 12:45
17/04 Analia -  T. Silva  -  saída 13:00   (  no lugar do Natan  )


VANESSA PACIULLO MAROSSI ==========
10/06 ANÁLIA Vanessa saída 13:00


VICTOR SAPOUNTZAKIS RIBEIRO ==========
03/06 Jabaquara  -  Sapountzakis saída 18:43
05/06 Osasco  -  Sapountzakis saída 23:31


VIVIAN CRISTINE DOS ANJOS E SILVA ==========
10/06 VILLA Vivian dispensada


VIVIANNA BOVERIO GALZERANI ==========
06/06 Itaim Vivianna dispensada
22/06 Osasco Vivianna saída 13:00   (  deslocada VNS  )


WANGLES PIGNATON DE PAULA ==========
Deslocado Villa (cirurgia a pedido)


YURI LUCAS DE SOUZA ==========
10:06 Osasco  -  Souza saída 13:40 (deslocado Morumbi)

In [53]:
len(fd)

427

# todos feitos por mim e o programa

In [54]:
fd = pd.DataFrame(columns=['nome', "mensagem", 'endereço'])

caminho = "C:/Users/Gabriel/Documents//PegaPlantão/03 2023"  # diretório atual, pode ser substituído pelo caminho desejado
pastas = next(os.walk(caminho))[1]

for pasta in pastas:
    caminho_1 = caminho+"/"+pasta
    #print(pasta, '='*10)
    for i in next(os.walk(caminho_1))[2]:
        if (i == 'df_giov.xlsx') or (i == 'df_giov2.xlsx') or (i == '_chat.txt'):
            continue
        else:
            caminho_2 = caminho+"/"+pasta+"/"+i
            
            df = pd.read_excel(caminho_2, usecols=['nome', "mensagem", ])
            print(pasta, '->', i, '->', len(df))
            
            df['endereço'] = pasta+' -> '+i+' -> '+str(len(df))
            
            fd = pd.concat([fd, df])
            fd.reset_index(drop=True, inplace=True)
            
fd

03(01a07) -> df.xlsx -> 416
03(01a07) -> df_gabs.xlsx -> 15
03(01a07) -> df_gabs2.xlsx -> 72
03(07a09) -> df.xlsx -> 129
03(07a09) -> df_gabs.xlsx -> 2
03(07a09) -> df_gabs2.xlsx -> 40
03(09a13) -> df.xlsx -> 232
03(09a13) -> df_gabs.xlsx -> 28
03(09a13) -> df_gabs2.xlsx -> 5
03(13a16) -> df.xlsx -> 181
03(13a16) -> df_gabs.xlsx -> 78
03(16a20) -> df.xlsx -> 222
03(16a20) -> df_gabs.xlsx -> 44
03(20a27) -> df.xlsx -> 447
03(20a27) -> df_gabs.xlsx -> 108
03(27a29) -> df.xlsx -> 109
03(27a29) -> df_gabs.xlsx -> 50

,nome,mensagem,endereço
0,MATHEUS ACQUESTA GAUBEUR,01/03 Villa - Matheus entrada 04:45,03(01a07) -> df.xlsx -> 416
1,GABRIEL GONDIM FONSECA,01/03 Itaim - Gondim entrada 05:15,03(01a07) -> df.xlsx -> 416
2,ELAINE IMAEDA DE MOURA,01/03 Anália Elaine entrada 05:30,03(01a07) -> df.xlsx -> 416
3,MANOEL DE SOUZA NETO,01/03 Santa Isabel Manoel entrada 05:20,03(01a07) -> df.xlsx -> 416
4,VITOR OLIVEIRA ANDRE,01/03 Itaim Vitor entrada 05:38,03(01a07) -> df.xlsx -> 416
...,...,...,...
2173,SIDNEY ORLANDO DE SOUZA,27/03-Itaim - Sidney- saida as 10:30.,03(27a29) -> df_gabs.xlsx -> 50
2174,SIDNEY ORLANDO DE SOUZA,28/03-Itaim- Sidney-saida as 16:40,03(27a29) -> df_gabs.xlsx -> 50
2175,THAIS MIRANDA RAMOS,28/03 JABAQUARA - Miranda saída às 14h15,03(27a29) -> df_gabs.xlsx -> 50
2176,VITOR OLIVEIRA ANDRE,28/03 VNS Vitor saída 18:00,03(27a29) -> df_gabs.xlsx -> 50
2177,VIVIAN CRISTINE DOS ANJOS E SILVA,28/03 VILLA Vivian saida 16:30,03(27a29) -> df_gabs.xlsx -> 50

In [59]:
"427 registros =>", str(round((427/2178)*100, 2))+"% de todos registros"

('427 registros =>', '19.61% de todos registros')